### ISSUE TITLE
Related posts

### ISSUE THREAD

**Issue by vlad706** [athemes/Cali#11]
On the single post design, there's a section called Related Posts.
At the moment it's coded to work as a prev/next post navigation. Which is okay because we can't/shouldn't have a related posts feature coded into the theme.

But the design needs to be changed, because now it does indeed look like a related posts section while functioning in fact like post navigation.
@CharlieLivingston @IgorMilosavljevic

**Comment by CharlieLivingston** [comment]
My hope was that it could actually display related posts by adding styling for something like https://en-gb.wordpress.org/plugins/related-posts-for-wp/

**Comment by vlad706** [comment]
@CharlieLivingston That can be done, sure.

But the problem here is that the post navigation is missing from the design.

**Comment by CharlieLivingston** [comment]
Ah I see. I'll ask Leonard.

**Comment by vlad706** [comment]
Since Igor already made the navigation with thumbnails, which I think is
cool, Leonard should be notified of that so he designs it in a way that it
includes thumbnails.
