### ISSUE TITLE
Highlighted post on archives

### ISSUE THREAD

**Issue by vlad706** [athemes/Cali#12]
There doesn't seem to be a way to show the highlighted post on archives, like it is in the design: https://projects.invisionapp.com/d/main#/console/12341577/267038233/preview

**Comment by CharlieLivingston** [comment]
This definitely was an option in Igor's http://mode-beta.pixoff.me/category/fashion/. That's how it was displaying by default until I changed it via a theme option I think.

From Slack (Igor quote): 

> Ah right, there are two options for the archive page
> This option can be created with selecting the archive pages to show the sidebar (if I'm correct in assuming the right side of the page is a sidebar), but I didn't add the option to show the first post on the archive page as "highlighter" ie. bigger.
> That should be a quick fix as I already have that layout on the home page

**Comment by vlad706** [comment]
@CharlieLivingston The option he's referring to is to show/hide the sidebar on archives.
There isn't an option to show the first post as highlighted, at least I don't see it.

**Comment by CharlieLivingston** [comment]
Oh wait, maybe you're right.

We did discuss this on Slack briefly before. This is what you said at the time: 

> Not sure I understand, are there options now to change the layout of the archive?
> I can't see them
> Can be ignored
> I think if we're showing the sidebar on the index, we should also show it on the archives by default
> Maybe without the highlighted post so that it is a bit different

**Comment by CharlieLivingston** [comment]
And this is what Igor said before:

> I can use a different format for the blog archive. Or can use object-fit like I did on the post slider. What do you prefer @vlad?
> @charlie  Currently you can have 3 column layout and 2 column layout with the sidebar
> I think the full option with the highlighted post isn't complicated

**Comment by vlad706** [comment]
Yep, we can have it without the highlighted post.

**Comment by vlad706** [comment]
Closing this as no changes are needed.
