### ISSUE TITLE
Fitvids

### ISSUE THREAD

**Issue by vlad706** [athemes/Cali#23]
Most likely we'll need to load Fitvids.

**Comment by IgorMilosavljevic** [comment]
Should we then enqueue main.min.js ?
As currently fitvid is not being loaded with main.js

**Comment by IgorMilosavljevic** [comment]
Fixed/solved with this commit [c273bd4](https://github.com/athemes/Cali/commit/c273bd47cb0c34cba73a53766d4c4c826dd344bf)
